name: 000-Setup

on:
  push:
    branches: ["main"]
    paths:
      - "**/Labs/000-Setup/**"
  pull_request:
    branches: ["main"]
    paths:
      - "**/Labs/000-Setup/**"

jobs:
  build:
    runs-on: ubuntu-latest
    # Execute the step demo to verify that all is working
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      - name: Test Lab
        working-directory: Labs/000-Setup
        run: bash ./_demo.sh
